from __future__ import annotations

from pydantic import BaseModel


class BasePdfPayload(BaseModel):
    """Shared base for all PDF document payloads generated by SecondStream agents.

    Provides the three fields that every PDF needs for its cover block and
    filename construction. DiscoveryReportPayload does NOT inherit from this —
    it uses `snapshot: str` for a different contract.
    """

    customer: str
    stream: str
    date: str
